SELECT SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO();

-- THIS IS A SAMPLE TABLE FOR ILLUSTRATION
create or replace TABLE FIRST_DB.FIRST_SCHEMA.ITEM (
	C1 NUMBER(38,0),
	C2 DATE,
	C3 VARCHAR(16777216),
	C4 NUMBER(38,0),
	C5 NUMBER(38,0)
);

-- CREATE EXTERNAL S3 INTEGRATION IN SNOWFLAKE
CREATE STORAGE INTEGRATION s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<your_AWS>:role/<your_IAM>'
  STORAGE_ALLOWED_LOCATIONS = ('*');

  DESC INTEGRATION s3_int;

select CURRENT_ROLE()

GRANT CREATE STAGE ON SCHEMA public TO ROLE snowflake_IAM;

GRANT USAGE ON INTEGRATION s3_int TO ROLE snowflake_IAM;

-- CREATE EXTERNAL STAGE IN SNOWFLAKE
CREATE STAGE my_s3_stage
  STORAGE_INTEGRATION = s3_int
  URL = 's3://<bucket/path>/'
  FILE_FORMAT = my_csv_format;

-- OPTIONAL: TRY TO LOAD SOME SAMPLE DATA FROM SNOWFLAKE INTERNAL STAGE  
  COPY INTO ITEM
  FROM @my_s3_stage
  PATTERN='.*Item.*.csv';

-- SNOWPIPE GENERATION FROM S3 TO SNOWFLAKE
  create pipe firstpipe auto_ingest=true as
  COPY INTO ITEM
  FROM @my_s3_stage
  PATTERN='.*Item.*.csv';

  show pipes

  select system$pipe_status('FIRSTPIPE')